# Use an official lightweight Python image
FROM python:3.12-slim

ENV PORT=8080

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    libffi-dev \
    libssl-dev \
    libblas-dev \
    liblapack-dev \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

# Copy files
COPY . .

# Install requirements
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt


# Expose port
EXPOSE ${PORT}

# Set default command (adjust if needed)
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:${PORT}"]
